# Generated by Django 5.0.6 on 2024-07-03 20:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'نام کاربری انتخاب شده قبلا استفاده شده است.'}, max_length=150, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر نیست.')])),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'نام کاربری انتخاب شده قبلا استفاده شده است.'}, max_length=150, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر نیست.')])),
                ('password', models.CharField(max_length=128)),
                ('raw_password', models.CharField(blank=True, max_length=128, null=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=50)),
                ('url_file', models.CharField(max_length=300)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('size', models.PositiveIntegerField()),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('accessible_users', models.ManyToManyField(related_name='accessible_objects', to='object.customuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to='object.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('accessible_users', models.ManyToManyField(related_name='accessible_user', to='object.customuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_file', to='object.customuser')),
            ],
        ),
    ]
