# Generated by Django 5.0.6 on 2024-06-30 00:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'نام کاربری انتخاب شده قبلا استفاده شده است.'}, max_length=150, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر نیست.')])),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons/')),
                ('size', models.PositiveIntegerField()),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('accessible_users', models.ManyToManyField(related_name='accessible_objects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
