# Generated by Django 5.0.6 on 2024-06-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstorage',
            name='accessible_users',
            field=models.ManyToManyField(related_name='accessible_objects', to='object.customuser'),
        ),
    ]
