# Generated by Django 4.2.13 on 2024-06-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
