# Generated by Django 5.0.6 on 2024-06-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_alter_objectstorage_accessible_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectstorage',
            name='opbect_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectstorage',
            name='url_file',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
