# Generated by Django 4.2.13 on 2024-06-30 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_customuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'نام کاربری انتخاب شده قبلا استفاده شده است.'}, max_length=150, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر نیست.')])),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
