# Generated by Django 5.0.6 on 2024-06-30 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_objectstorage_opbect_name_objectstorage_url_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectstorage',
            old_name='opbect_name',
            new_name='opject_name',
        ),
    ]
