# Generated by Django 5.0.6 on 2024-06-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_rename_opbect_name_objectstorage_opject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectstorage',
            old_name='opject_name',
            new_name='object_name',
        ),
    ]
