# Generated by Django 4.2.13 on 2024-06-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_tempuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
